name: snowroute
description: A sample web application
dependencies:
  browser: any
  google_maps: any
  polymer: any
  core_elements: any
  paper_elements: any
  google_maps: any
  
dev_dependencies:
  unittest: any
  
transformers:
- polymer:
    entry_points: web/index.html
